name: cline_feed_server
description: A Serverpod server for generating Atom feeds for Cline's blog.
version: 0.1.0
homepage: https://github.com/cline/cline_feed_server

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 2.9.1
  http: ^1.4.0
  html: ^0.15.5
  xml: ^6.5.0
  intl: ^0.20.2

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: 2.9.1

